### PR TITLE
added in getters

### PR DESCRIPTION
**Pull request by Nnoremacc**

### CODE REVIEW

**Comment by cerisewuthrich** [comment]
Some of the getters don't match the function names that are in RepairOrder.java
Please check spelling/case and re-commit

**Comment by cerisewuthrich** [comment]
@Nnoremacc , please make the requested changes

**Comment by Nnoremacc** [comment]
CID is a foreign key for the repairOrder table though. you want to remove
it?
you want me to fix the repairOrder.java in the core as well? I didn't do
that one

**Comment by cerisewuthrich** [comment]
1.  When I looked at your latest pull request, it showed that you added 3 files to the commit including RepairOrder.java
2.  When I look at the RepairOrder.java file that is part of the pull request, there are 3 private data members pertaining to carrier ID.  We only need 2.  The Carrier ID who delivered the item(s) to be repaired and the Carrier ID of who the repaired equipment is shipped out with.  Why would we need a 3rd Carrier ID?

**Pull request closed without merging**
